version: "3.8"
services:
  backend:
    image: "jaygibran/springboot-react-fullstack:9.5.2021.16.4.16"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev