version: "3.8"
services:
  backend:
    image: "jaygibran/springboot-react-fullstack:13.5.2021.21.26.59"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev